version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: nest_backend
    network_mode: host
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - frontend
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  pgdata:
